variables: 
    DEPENDENCIES: 
        "build-essential 
        git
        cmake 
        libboost1.63-dev
        liblemon-dev
        def
        lef
        ophidian-units
        libflute-dev
        libverilog-parser-dev"
    BUILD_LOCAL_DEPENDENCIES:
        "build-essential 
        git
        cmake 
        libboost1.63-dev
        libz-dev
        flex 
        bison
        libbison-dev"
    DEPENDENCIES_UBUNTU_BIONIC:
        "build-essential 
        git
        cmake 
        libboost-dev
        liblemon-dev
        def
        lef
        ophidian-units
        libflute-dev
        libverilog-parser-dev"
    GIT_SUBMODULE_STRATEGY: recursive

stages:
    - build

build_on_debian-buster:
    image: debian:buster
    stage: build
    before_script:
        - apt-get update -qq && apt-get install -qq -y software-properties-common gpg
        - apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A62C1A5EFCB3D41A1FDB35758179B53998C15E64 && apt-get update -qq
        - add-apt-repository -y -u -m "deb http://ppa.launchpad.net/eclufsc/ophidian/ubuntu artful main"
        - apt-get install -qq -y $DEPENDENCIES
    script:
        - mkdir build && cd build
        - cmake -DCMAKE_INSTALL_PREFIX=/usr 
                -DCMAKE_BUILD_TYPE=Release 
                ..
        - make -j2
        - cd test
        - ./ophidian_tests
    artifacts:
        paths:
          - build/

build_on_debian-sid:
    image: debian:sid
    stage: build
    before_script:
        - apt-get update -qq && apt-get install -qq -y software-properties-common gpg
        - apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A62C1A5EFCB3D41A1FDB35758179B53998C15E64 && apt-get update -qq
        - add-apt-repository -y -u -m -k hkp://keyserver.ubuntu.com:80 "deb http://ppa.launchpad.net/eclufsc/ophidian/ubuntu artful main"
        - apt-get install -qq -y $DEPENDENCIES
    script:
        - mkdir build && cd build
        - cmake -DCMAKE_INSTALL_PREFIX=/usr 
                -DCMAKE_BUILD_TYPE=Release 
                ..
        - make -j2
        - cd test
        - ./ophidian_tests
    artifacts:
        paths:
            - build/

build_on_ubuntu-artful:
    image: ubuntu:artful
    stage: build
    before_script:
        - apt-get update -qq && apt-get install -qq -y software-properties-common
        - add-apt-repository -y -u ppa:eclufsc/ophidian
        - apt-get install -qq -y $DEPENDENCIES
    script:
        - mkdir build && cd build
        - cmake -DCMAKE_INSTALL_PREFIX=/usr 
                -DCMAKE_BUILD_TYPE=Release 
                ..
        - make -j2
        - cd test
        - ./ophidian_tests
    artifacts:
        paths:
            - build/

build_on_ubuntu-bionic:
    image: ubuntu:bionic
    stage: build
    before_script:
        - apt-get update -qq && apt-get install -qq -y software-properties-common
        - add-apt-repository -y ppa:eclufsc/ophidian && apt-get update -qq
        - apt-get install -qq -y $DEPENDENCIES_UBUNTU_BIONIC
    script:
        - mkdir build && cd build
        - cmake -DCMAKE_INSTALL_PREFIX=/usr 
                -DCMAKE_BUILD_TYPE=Release 
                ..
        - make -j2
        - cd test
        - ./ophidian_tests
    artifacts:
        paths:
            - build/

build_using_dependencies_script_on_source:
    image: ubuntu:artful
    stage: build
    before_script:
        - apt-get update -qq && apt-get install -qq -y $BUILD_LOCAL_DEPENDENCIES
    script:
        - echo "y" | bash build_dependencies.sh
        - mkdir build && cd build
        - cmake -DCMAKE_INSTALL_PREFIX=/usr 
                -DCMAKE_BUILD_TYPE=Release
                ..
        - make -j2
        - cd test
        - ./ophidian_tests
    artifacts:
        paths:
            - build/

build_using_dependencies_script_on_sistem:
    image: ubuntu:artful
    stage: build
    before_script:
        - apt-get update -qq && apt-get install -qq -y $BUILD_LOCAL_DEPENDENCIES
    script:
        - echo y | bash build_dependencies.sh --install_to /usr/local
        - mkdir build && cd build
        - cmake -DCMAKE_INSTALL_PREFIX=/usr 
                -DCMAKE_BUILD_TYPE=Release
                ..
        - make -j2
        - cd test
        - ./ophidian_tests
    artifacts:
        paths:
            - build/
