language: cpp

sudo: required
dist: trusty

compiler:
  - gcc

before_script:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install g++-4.9
  - mkdir build && cd build
  - wget http://ftp.gnu.org/gnu/bison/bison-3.0.4.tar.gz
  - tar -zxvf bison-3.0.4.tar.gz
  - cd bison-3.0.4
  - mkdir inst
  - ./configure --prefix=$PWD/inst
  - make -j && make install
  - cd inst/bin
  - export PATH=$PWD:$PATH
  - cd ..
  - cd ..
  - cd ..
  - cmake ..

script: make -j && make -j test
