language: cpp

sudo: required
dist: trusty

compiler:
    - gcc

before_script:
  - mkdir build && cd build
  - wget http://ftp.gnu.org/gnu/bison/bison-3.0.4.tar.gz
  - tar -zxvf bison-3.0.4.tar.gz
  - cd bison-3.0.4
  - mkdir inst
  - ./configure --prefix=inst
  - make && make install
  - cd inst/bin
  - export PATH=$PATH:$PWD
  - cd ../..
  - make
  - make install
  - cmake ..

script: make && make test
